### ISSUE TITLE
Server Settings

### ISSUE THREAD

**Issue by dvrg** [digital-inovasi-bangsa/Laravel-Module-Smartedu#99]
- [x] Setup domain baru pada server
- [x] Integrasi weebhooks
- [x] Install supervisor
- [x] Sesuaikan settingan supervisor dengan kebutuhan @rrozaq 
- [x] Error saat install package.json (Ada beberapa package yang tidak ketemu)

**Comment by dvrg** [comment]
Current config, name **laravel-worker.conf**
```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/vhosts/smart-edu.id/api.smart-edu.my.id/artisan queue:work sqs --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/vhosts/smart-edu.id/api.smart-edu.my.id/worker.log
stopwaitsecs=3600
```

**Comment by kiss985632** [comment]
> Current config, name **laravel-worker.conf**
> 
> ```
> 
> [program:laravel-worker]
> 
> process_name=%(program_name)s_%(process_num)02d
> 
> command=php /var/www/vhosts/smart-edu.id/api.smart-edu.my.id/artisan queue:work sqs --sleep=3 --tries=3 --max-time=3600
> 
> autostart=true
> 
> autorestart=true
> 
> user=root
> 
> numprocs=8
> 
> redirect_stderr=true
> 
> stdout_logfile=/var/www/vhosts/smart-edu.id/api.smart-edu.my.id/worker.log
> 
> stopwaitsecs=3600
> 
> ```
> 
> 
> 
> How to run 
> 
> ```
> 
> $ sudo supervisorctl reread
> 
> 
> 
> $ sudo supervisorctl update
> 
> 
> 
> $ sudo supervisorctl start laravel-worker:*
> 
> ```
